# Universal Quick Makefile for Small Projects
# Author: Ethan Cho (ethanwonc@iCloud.com)
# Version: 24.05

c: main.c
	gcc -o main -Wall -Wextra -Werror -pedantic main.c
	./main

cpp: main.cpp
	g++ -o main -Wall -Wextra -Werror -pedantic main.cpp
	./main
